name = "oxlisvoid-com"
main = "worker.js"
compatibility_date = "2026-09-06"

[assets]
directory = "./public"
not_found_handling = "single-page-application"
binding = "ASSETS"

[vars]
PAYPAL_ENV = "sandbox"
PAYPAL_CLIENT_ID = "BAAKh72P0JbRLyfjDWIBGR-WtlMkX2U1WHk1R8RyX3IyXb3gHAxLEymZW3EZ6gn5acIRAVJ9xViiWgs0O4"
PAYPAL_CLIENT_SECRET = "EBifyADQMZLX6zcqdG_Sh7Qx1a3dEWjX9GYb510c7n-rAbbbki1217jcBJwChvw0XK-CZyWmzdLSIozx"
