name = "oxlisvoid-com"
main = "worker.js"
compatibility_date = "2026-09-06"

[assets]
directory = "./public"
not_found_handling = "single-page-application"

[vars]
PAYPAL_ENV = "live"
# Secrets must be set in Cloudflare Dashboard:
# PAYPAL_CLIENT_ID = BAAdXauohccGYk8cZbH4lDfMi6Q6BPwwi39HJOHPAjoMbRURbUFM5iGhTtNmp2qviwo7Epa_sP_zpi1NkQ
# PAYPAL_CLIENT_SECRET = EH5wiOaR-L44exNiXtoIdEpY43EFNEe-FZglkwGQY4bVotW_p_boMnxtIkNhfsW6jcVwdfhO10a2IEMm

# Build config for Cloudflare Pages/Workers Builds
[build]
command = ""
