name = "oxlisvoid-com"
main = "worker.js"
compatibility_date = "2026-09-06"

[assets]
directory = "./public"
not_found_handling = "single-page-application"
binding = "ASSETS"

[vars]
PAYPAL_ENV = "sandbox"
PAYPAL_CLIENT_ID = BAArbXEViQ9tTcf4iujvXjW5B9OZ_mlOsfQeHp_9LJSvnanGjdTWSkzCGyj9k9Fg3_rcUIAK3Xn4ILAquI
PAYPAL_CLIENT_SECRET = EJdXpGaVKYQ977IQyIQgNKOtvudwjpMYs8OzpQvXG89JT5bJpAbu7ZE2L10zUq7zx36nOVsxrDmOJdBc
